default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: circleci_docker_user
  password: circleci_docker_user
  timeout: 5000

development:
  <<: *default
  database: circleci_docker_development

test:
  <<: *default
  database: circleci_docker_test

production:
  <<: *default
  database: circleci_docker_production

build:
  <<: *default
  database: circleci_docker_build
